version: '3.8'

services:
  study:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "until nc -z db 5432; do echo 'Waiting for db...'; sleep 1; done;
               cd study &&
               uv run python manage.py makemigrations &&
               uv run python manage.py migrate &&
               uv run python manage.py collectstatic --noinput &&
               uv run gunicorn --bind 0.0.0.0:8000 study.conf.wsgi:application"
    

    ports:
      - "8000:8000"
    environment:
      - DEBUG=1

    depends_on:
      - db
    volumes:
      - static:/var/static
      - media:/var/uploads
    networks:
      - mynetwork

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=198616Gm
      - POSTGRES_DB=study
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - mynetwork


  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - media:/var/uploads/
      - static:/var/static/


    depends_on:
      - study
    networks:
      - mynetwork

volumes:
  db_data:
  static_volume:
  media_volume:
  static:
  media:

networks:
  mynetwork:
    driver: bridge
