line-length = 120  # Совместимость с Black и Flake8
exclude = [
    ".git",
    "__pycache__",
    "*.yml.enc",
    "study/db/migrations/*",

]  # Исключение файлов и директорий

[lint]
select = ["E", "F", "W", "I", "B"]  # Включение необходимых проверок
fixable = ["I", "E", "W"]  # Автоисправление для импортов и форматирования

ignore = ["B904", "B008"]  # Игнорировать конкретные правила